/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rentkuyyoi;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JTable;

/**
 *
 * @author Firhan
 */
public class AllTransaksi extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel6
     */
    public AllTransaksi() {
        initComponents();
    }

    public JButton getBTNkembali() {
        return BTNkembali;
    }

    public JTable getTableTransaksi() {
        return TableTransaksi;
    }

    public void setTableTransaksi(JTable TableTransaksi) {
        this.TableTransaksi = TableTransaksi;
    }
    
    public void addListener(ActionListener e){
        BTNkembali.addActionListener(e);
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableTransaksi = new javax.swing.JTable();
        BTNkembali = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        jInternalFrame1.setTitle("View");
        jInternalFrame1.setVisible(true);
        jInternalFrame1.getContentPane().setLayout(null);
        jInternalFrame1.getContentPane().add(jLabel1);
        jLabel1.setBounds(315, 58, 0, 0);

        jLabel2.setIcon(new javax.swing.ImageIcon("E:\\K u l i a h\\Pemrograman Berorientasi Objek (PBO)\\TubesKelompok3\\NetBeansProjects\\NetBeansProjects\\RentKuyYoi\\src\\rentkuyyoi\\logo-mobil3.png")); // NOI18N
        jInternalFrame1.getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 10, 360, 120);

        jPanel1.setBackground(new java.awt.Color(195, 152, 107));
        jPanel1.setLayout(null);

        TableTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id Transaksi", "Tipe Mobil", "Tanggal peminjaman", "Tanggal pengembalian"
            }
        ));
        TableTransaksi.setToolTipText("");
        jScrollPane1.setViewportView(TableTransaksi);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 40, 530, 100);

        jInternalFrame1.getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 150, 560, 170);

        BTNkembali.setText("Kembali");
        jInternalFrame1.getContentPane().add(BTNkembali);
        BTNkembali.setBounds(139, 370, 90, 23);

        jLabel7.setIcon(new javax.swing.ImageIcon("E:\\K u l i a h\\Pemrograman Berorientasi Objek (PBO)\\TubesKelompok3\\NetBeansProjects\\NetBeansProjects\\RentKuyYoi\\src\\rentkuyyoi\\bg.jpg")); // NOI18N
        jInternalFrame1.getContentPane().add(jLabel7);
        jLabel7.setBounds(0, -40, 860, 520);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNkembali;
    private javax.swing.JTable TableTransaksi;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
