/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rentkuyyoi;

import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author Firhan
 */
public class Home extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel4
     */
    public Home() {
        initComponents();
    }

    public JButton getStartButton() {
        return startButton;
    }
    
    public void addListener(ActionListener e){
        startButton.addActionListener(e);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        startButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jInternalFrame1.setTitle("Home");
        jInternalFrame1.setVisible(true);
        jInternalFrame1.getContentPane().setLayout(null);
        jInternalFrame1.getContentPane().add(jLabel1);
        jLabel1.setBounds(315, 58, 0, 0);

        jLabel2.setIcon(new javax.swing.ImageIcon("E:\\K u l i a h\\Pemrograman Berorientasi Objek (PBO)\\TubesKelompok3\\NetBeansProjects\\NetBeansProjects\\RentKuyYoi\\src\\rentkuyyoi\\logo-mobil3.png")); // NOI18N
        jInternalFrame1.getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 10, 360, 120);

        startButton.setBackground(new java.awt.Color(153, 153, 153));
        startButton.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        startButton.setForeground(new java.awt.Color(0, 0, 255));
        startButton.setIcon(new javax.swing.ImageIcon("E:\\K u l i a h\\Pemrograman Berorientasi Objek (PBO)\\TubesKelompok3\\NetBeansProjects\\NetBeansProjects\\RentKuyYoi\\src\\rentkuyyoi\\StartButton.png")); // NOI18N
        startButton.setBorder(null);
        jInternalFrame1.getContentPane().add(startButton);
        startButton.setBounds(230, 330, 90, 90);

        jLabel3.setFont(new java.awt.Font("Cambria Math", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(231, 0, 0));
        jLabel3.setText("RENT...");
        jInternalFrame1.getContentPane().add(jLabel3);
        jLabel3.setBounds(300, 270, 180, 50);

        jLabel4.setFont(new java.awt.Font("Cambria Math", 1, 48)); // NOI18N
        jLabel4.setText("READY.");
        jInternalFrame1.getContentPane().add(jLabel4);
        jLabel4.setBounds(130, 160, 180, 50);

        jLabel5.setFont(new java.awt.Font("Cambria Math", 1, 48)); // NOI18N
        jLabel5.setText("SET.");
        jInternalFrame1.getContentPane().add(jLabel5);
        jLabel5.setBounds(250, 210, 120, 60);

        jLabel7.setIcon(new javax.swing.ImageIcon("E:\\K u l i a h\\Pemrograman Berorientasi Objek (PBO)\\TubesKelompok3\\NetBeansProjects\\NetBeansProjects\\RentKuyYoi\\src\\rentkuyyoi\\bg.jpg")); // NOI18N
        jInternalFrame1.getContentPane().add(jLabel7);
        jLabel7.setBounds(0, -40, 860, 520);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton startButton;
    // End of variables declaration//GEN-END:variables
}
