/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rentkuyyoi;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author RIZKY RAMADIKA
 */
public class IsiCustomer1 extends javax.swing.JPanel {

    /**
     * Creates new form IsiCustomer1
     */
    public IsiCustomer1() {
        initComponents();
    }
    
    public JButton getBTNlanjut5() {
        return BTNlanjut5;
    }

    public JTextArea getTXTalamat() {
        return TXTalamat;
    }

    public JTextField getTXTnamacus() {
        return TXTnamacus;
    }

    public JTextField getTXTnomorkntk() {
        return TXTnomorkntk;
    }
    
    public void addListener(ActionListener e){
        BTNlanjut5.addActionListener(e);
    }
    
    public void reset(){
        TXTalamat.setText("");
        TXTnamacus.setText("");
        TXTnomorkntk.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        TXTnamacus = new javax.swing.JTextField();
        TXTnomorkntk = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TXTalamat = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        BTNlanjut5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(195, 152, 107));

        label1.setText("Nama Customer");

        label2.setText("Alamat Customer");

        label3.setText("Nomor Kontak");

        TXTnomorkntk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTnomorkntkActionPerformed(evt);
            }
        });

        TXTalamat.setColumns(20);
        TXTalamat.setRows(5);
        jScrollPane1.setViewportView(TXTalamat);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TXTnamacus)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                    .addComponent(TXTnomorkntk))
                .addGap(42, 42, 42))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXTnamacus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXTnomorkntk, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("E:\\K u l i a h\\Pemrograman Berorientasi Objek (PBO)\\TubesKelompok3\\NetBeansProjects\\NetBeansProjects\\RentKuyYoi\\src\\rentkuyyoi\\logo-mobil3.png")); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 360, -1));

        BTNlanjut5.setText("Lanjut");
        BTNlanjut5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNlanjut5ActionPerformed(evt);
            }
        });
        add(BTNlanjut5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 73, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rentkuyyoi/bg.jpg"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 630, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void TXTnomorkntkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTnomorkntkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTnomorkntkActionPerformed

    private void BTNlanjut5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNlanjut5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNlanjut5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNlanjut5;
    private javax.swing.JTextArea TXTalamat;
    private javax.swing.JTextField TXTnamacus;
    private javax.swing.JTextField TXTnomorkntk;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    // End of variables declaration//GEN-END:variables
}
