/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rentkuyyoi;

import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author Firhan
 */
public class menupilihan extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel5
     */
    public menupilihan() {
        initComponents();
    }

    public JButton getBTNlihatdata() {
        return BTNlihatdata;
    }

    public JButton getBTNpengembalian() {
        return BTNpengembalian;
    }

    public JButton getBTNpenyewaan() {
        return BTNpenyewaan;
    }
    
    public void addListener(ActionListener e){
        BTNlihatdata.addActionListener(e);
        BTNpengembalian.addActionListener(e);
        BTNpenyewaan.addActionListener(e);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BTNpengembalian = new javax.swing.JButton();
        BTNpenyewaan = new javax.swing.JButton();
        BTNlihatdata = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        jInternalFrame1.setTitle("Menu");
        jInternalFrame1.setVisible(true);
        jInternalFrame1.getContentPane().setLayout(null);
        jInternalFrame1.getContentPane().add(jLabel1);
        jLabel1.setBounds(315, 58, 0, 0);

        jLabel2.setIcon(new javax.swing.ImageIcon("E:\\K u l i a h\\Pemrograman Berorientasi Objek (PBO)\\TubesKelompok3\\NetBeansProjects\\NetBeansProjects\\RentKuyYoi\\src\\rentkuyyoi\\logo-mobil3.png")); // NOI18N
        jInternalFrame1.getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 10, 360, 120);

        BTNpengembalian.setText("Pengembalian");
        BTNpengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNpengembalianActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(BTNpengembalian);
        BTNpengembalian.setBounds(210, 240, 180, 23);

        BTNpenyewaan.setText("Penyewaan");
        jInternalFrame1.getContentPane().add(BTNpenyewaan);
        BTNpenyewaan.setBounds(250, 300, 100, 23);

        BTNlihatdata.setText("Lihat Data");
        jInternalFrame1.getContentPane().add(BTNlihatdata);
        BTNlihatdata.setBounds(250, 180, 100, 23);

        jLabel7.setIcon(new javax.swing.ImageIcon("E:\\K u l i a h\\Pemrograman Berorientasi Objek (PBO)\\TubesKelompok3\\NetBeansProjects\\NetBeansProjects\\RentKuyYoi\\src\\rentkuyyoi\\bg.jpg")); // NOI18N
        jInternalFrame1.getContentPane().add(jLabel7);
        jLabel7.setBounds(0, -40, 860, 520);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BTNpengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNpengembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNpengembalianActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNlihatdata;
    private javax.swing.JButton BTNpengembalian;
    private javax.swing.JButton BTNpenyewaan;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
