/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rentkuyyoi;

import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JSpinner;
import javax.swing.JTextField;

/**
 *
 * @author Firhan
 */
public class Pengembalian extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel7
     */
    public Pengembalian() {
        initComponents();
    }

    public JButton getBTNkembali1() {
        return BTNkembali1;
    }

    public JButton getBTNkonfirmasi() {
        return BTNkonfirmasi;
    }

    public JButton getBTNok() {
        return BTNok;
    }

    public JTextField getTXTdenda() {
        return TXTdenda;
    }

    public JTextField getTXTidTransaksi() {
        return TXTidTransaksi;
    }

    public JComboBox getCMBOXbulankembali() {
        return CMBOXbulankembali;
    }

    public JComboBox getCMBOXbulanpinjam() {
        return CMBOXbulanpinjam;
    }

    public JComboBox getCMBOXtahunkembali() {
        return CMBOXtahunkembali;
    }

    public JComboBox getCMBOXtahunpinjam() {
        return CMBOXtahunpinjam;
    }

    public JComboBox getCMBOXtanggalkembali() {
        return CMBOXtanggalkembali;
    }

    public JComboBox getCMBOXtanggalpinjam() {
        return CMBOXtanggalpinjam;
    }
    
    public int getPinjamTanggal() {
        return CMBOXtanggalpinjam.getSelectedIndex() + 1;    
    }
    
    public int getPinjamBulan() {
        return CMBOXbulanpinjam.getSelectedIndex() + 1;    
    }
    
    public int getKembaliTanggal() {
        return CMBOXtanggalkembali.getSelectedIndex() + 1;    
    }
    
    public int getKembaliBulan() {
        return CMBOXbulankembali.getSelectedIndex() + 1;    
    }
    
    
    public void setTXTdenda(int denda) {
        this.TXTdenda.setText(String.valueOf(denda));
    }
   
    public void reset(){
        CMBOXtanggalpinjam.setSelectedIndex(0);
        CMBOXbulanpinjam.setSelectedIndex(0);
        CMBOXtahunpinjam.setSelectedIndex(0);
        CMBOXtanggalkembali.setSelectedIndex(0);
        CMBOXbulankembali.setSelectedIndex(0);
        CMBOXtahunkembali.setSelectedIndex(0);
        TXTdenda.setText("");
        TXTidTransaksi.setText("");
    }
    
    public void addListener(ActionListener e){
        BTNkembali1.addActionListener(e);
        BTNkonfirmasi.addActionListener(e);
        BTNok.addActionListener(e);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TXTidTransaksi = new javax.swing.JTextField();
        TXTdenda = new javax.swing.JTextField();
        BTNok = new javax.swing.JButton();
        CMBOXbulanpinjam = new javax.swing.JComboBox();
        CMBOXtanggalpinjam = new javax.swing.JComboBox();
        CMBOXtahunpinjam = new javax.swing.JComboBox();
        CMBOXbulankembali = new javax.swing.JComboBox();
        CMBOXtanggalkembali = new javax.swing.JComboBox();
        CMBOXtahunkembali = new javax.swing.JComboBox();
        BTNkembali1 = new javax.swing.JButton();
        BTNkonfirmasi = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        jInternalFrame1.setTitle("Pengembalian");
        jInternalFrame1.setVisible(true);
        jInternalFrame1.getContentPane().setLayout(null);
        jInternalFrame1.getContentPane().add(jLabel1);
        jLabel1.setBounds(315, 58, 0, 0);

        jLabel2.setIcon(new javax.swing.ImageIcon("E:\\K u l i a h\\Pemrograman Berorientasi Objek (PBO)\\TubesKelompok3\\NetBeansProjects\\NetBeansProjects\\RentKuyYoi\\src\\rentkuyyoi\\logo-mobil3.png")); // NOI18N
        jInternalFrame1.getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 10, 360, 120);

        jPanel1.setBackground(new java.awt.Color(195, 152, 107));

        jLabel3.setText("ID Transaksi");

        jLabel4.setText("Tgl Peminjaman");

        jLabel5.setText("Tgl Pengembalian");

        jLabel6.setText("Denda");

        BTNok.setText("OK");
        BTNok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNokActionPerformed(evt);
            }
        });

        CMBOXbulanpinjam.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "september", "Oktober", "November", "Desember" }));

        CMBOXtanggalpinjam.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        CMBOXtahunpinjam.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2017", " " }));

        CMBOXbulankembali.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "september", "Oktober", "November", "Desember" }));

        CMBOXtanggalkembali.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        CMBOXtahunkembali.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2017" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(87, 87, 87)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TXTidTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(CMBOXbulanpinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CMBOXbulankembali, 0, 1, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(CMBOXtanggalkembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(CMBOXtahunkembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BTNok))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(CMBOXtanggalpinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(CMBOXtahunpinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(139, 139, 139)
                        .addComponent(TXTdenda, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3))
                    .addComponent(TXTidTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(CMBOXbulanpinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CMBOXtanggalpinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CMBOXtahunpinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(CMBOXbulankembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CMBOXtanggalkembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CMBOXtahunkembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNok))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel6))
                    .addComponent(TXTdenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2))
        );

        jInternalFrame1.getContentPane().add(jPanel1);
        jPanel1.setBounds(30, 140, 500, 190);

        BTNkembali1.setText("Kembali");
        jInternalFrame1.getContentPane().add(BTNkembali1);
        BTNkembali1.setBounds(109, 360, 100, 23);

        BTNkonfirmasi.setText("Konfirmasi");
        jInternalFrame1.getContentPane().add(BTNkonfirmasi);
        BTNkonfirmasi.setBounds(250, 360, 100, 23);

        jLabel7.setIcon(new javax.swing.ImageIcon("E:\\K u l i a h\\Pemrograman Berorientasi Objek (PBO)\\TubesKelompok3\\NetBeansProjects\\NetBeansProjects\\RentKuyYoi\\src\\rentkuyyoi\\bg.jpg")); // NOI18N
        jInternalFrame1.getContentPane().add(jLabel7);
        jLabel7.setBounds(0, -40, 860, 520);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BTNokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNokActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNkembali1;
    private javax.swing.JButton BTNkonfirmasi;
    private javax.swing.JButton BTNok;
    private javax.swing.JComboBox CMBOXbulankembali;
    private javax.swing.JComboBox CMBOXbulanpinjam;
    private javax.swing.JComboBox CMBOXtahunkembali;
    private javax.swing.JComboBox CMBOXtahunpinjam;
    private javax.swing.JComboBox CMBOXtanggalkembali;
    private javax.swing.JComboBox CMBOXtanggalpinjam;
    private javax.swing.JTextField TXTdenda;
    private javax.swing.JTextField TXTidTransaksi;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
