/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rentkuyyoi;

import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.util.Date;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JRadioButton;
import javax.swing.JSpinner;

/**
 *
 * @author Firhan
 */
public class PilihTransaksi extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public PilihTransaksi() {
        initComponents();
    }

    public JButton getBTNlanjut1() {
        return BTNlanjut1;
    }

    public JRadioButton getRdBTNAll() {
        return RdBTNAll;
    }

    public JButton getBTNkembali() {
        return BTNkembali;
    }
    
    public JRadioButton getRdBTNFasilitas() {
        return RdBTNFasilitas;
    }

    public JRadioButton getRdBTNSopir() {
        return RdBTNSopir;
    }

    public JComboBox getCMBOXbulankembali() {
        return CMBOXbulankembali;
    }

    public JComboBox getCMBOXbulanpinjam() {
        return CMBOXbulanpinjam;
    }

    public JComboBox getCMBOXtahunkembali() {
        return CMBOXtahunkembali;
    }

    public JComboBox getCMBOXtahunpinjam() {
        return CMBOXtahunpinjam;
    }

    public JComboBox getCMBOXtanggalkembali() {
        return CMBOXtanggalkembali;
    }

    public JComboBox getCMBOXtanggalpinjam() {
        return CMBOXtanggalpinjam;
    }

    public int getPinjamTanggal() {
        return CMBOXtanggalpinjam.getSelectedIndex() + 1;    
    }
    
    public int getPinjamBulan() {
        return CMBOXbulanpinjam.getSelectedIndex() + 1;    
    }
    
    public int getKembaliTanggal() {
        return CMBOXtanggalkembali.getSelectedIndex() + 1;    
    }
    
    public int getKembaliBulan() {
        return CMBOXbulankembali.getSelectedIndex() + 1;    
    }
    
    public JComboBox<String> getComboboxMobil() {
        return comboboxMobil;
    }

    public ButtonGroup getButtonGroup1() {
        return buttonGroup1;
    }
    
    public void addListener(ActionListener e){
        BTNlanjut1.addActionListener(e);
        RdBTNAll.addActionListener(e);
        RdBTNFasilitas.addActionListener(e);
        RdBTNSopir.addActionListener(e);
        BTNkembali.addActionListener(e);
    }
    
   
    public void reset(){
        comboboxMobil.setSelectedIndex(0);
        CMBOXtanggalpinjam.setSelectedIndex(0);
        CMBOXbulanpinjam.setSelectedIndex(0);
        CMBOXtahunpinjam.setSelectedIndex(0);
        CMBOXtanggalkembali.setSelectedIndex(0);
        CMBOXbulankembali.setSelectedIndex(0);
        CMBOXtahunkembali.setSelectedIndex(0);
        buttonGroup1.setSelected(null, true);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jFrame2 = new javax.swing.JFrame();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        comboboxMobil = new javax.swing.JComboBox<String>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        RdBTNFasilitas = new javax.swing.JRadioButton();
        RdBTNSopir = new javax.swing.JRadioButton();
        RdBTNAll = new javax.swing.JRadioButton();
        CMBOXbulanpinjam = new javax.swing.JComboBox();
        CMBOXtanggalpinjam = new javax.swing.JComboBox();
        CMBOXtahunpinjam = new javax.swing.JComboBox();
        CMBOXtahunkembali = new javax.swing.JComboBox();
        CMBOXtanggalkembali = new javax.swing.JComboBox();
        CMBOXbulankembali = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        BTNlanjut1 = new javax.swing.JButton();
        BTNkembali = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jInternalFrame1.setTitle("Pilih Transaksi");
        jInternalFrame1.setVisible(true);
        jInternalFrame1.getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(195, 152, 107));

        comboboxMobil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "- PILIH -", "SUV", "MPV", "City Car" }));
        comboboxMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihtypemobilActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Type Mobil               : ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Tgl Peminjaman       :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Tgl Pengembalian     :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Fasilitas                    :");

        RdBTNFasilitas.setBackground(new java.awt.Color(195, 152, 107));
        buttonGroup1.add(RdBTNFasilitas);
        RdBTNFasilitas.setText("Tanpa Fasilitas");
        RdBTNFasilitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdBTNFasilitasActionPerformed(evt);
            }
        });

        RdBTNSopir.setBackground(new java.awt.Color(195, 152, 107));
        buttonGroup1.add(RdBTNSopir);
        RdBTNSopir.setText("Dengan Sopir");

        RdBTNAll.setBackground(new java.awt.Color(195, 152, 107));
        buttonGroup1.add(RdBTNAll);
        RdBTNAll.setText("Sopir & BBM");

        CMBOXbulanpinjam.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "september", "Oktober", "November", "Desember" }));

        CMBOXtanggalpinjam.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        CMBOXtahunpinjam.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2017", " " }));

        CMBOXtahunkembali.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2017" }));

        CMBOXtanggalkembali.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        CMBOXbulankembali.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "september", "Oktober", "November", "Desember" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RdBTNAll)
                    .addComponent(RdBTNSopir)
                    .addComponent(RdBTNFasilitas)
                    .addComponent(comboboxMobil, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(CMBOXbulanpinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CMBOXtanggalpinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CMBOXtahunpinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(CMBOXbulankembali, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CMBOXtanggalkembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CMBOXtahunkembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(CMBOXbulanpinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CMBOXtanggalpinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CMBOXtahunpinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(comboboxMobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(CMBOXbulankembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CMBOXtanggalkembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CMBOXtahunkembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(RdBTNFasilitas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RdBTNSopir))
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RdBTNAll)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jInternalFrame1.getContentPane().add(jPanel1);
        jPanel1.setBounds(40, 120, 490, 220);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\K u l i a h\\Pemrograman Berorientasi Objek (PBO)\\TubesKelompok3\\NetBeansProjects\\NetBeansProjects\\RentKuyYoi\\src\\rentkuyyoi\\logo-mobil3.png")); // NOI18N
        jInternalFrame1.getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 0, 350, 130);

        BTNlanjut1.setText("Lanjut");
        jInternalFrame1.getContentPane().add(BTNlanjut1);
        BTNlanjut1.setBounds(150, 400, 73, 23);

        BTNkembali.setText("Kembali");
        jInternalFrame1.getContentPane().add(BTNkembali);
        BTNkembali.setBounds(240, 400, 69, 23);

        jLabel7.setIcon(new javax.swing.ImageIcon("E:\\K u l i a h\\Pemrograman Berorientasi Objek (PBO)\\TubesKelompok3\\NetBeansProjects\\NetBeansProjects\\RentKuyYoi\\src\\rentkuyyoi\\bg.jpg")); // NOI18N
        jInternalFrame1.getContentPane().add(jLabel7);
        jLabel7.setBounds(0, -40, 860, 520);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );

        try {
            jInternalFrame1.setIcon(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void pilihtypemobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihtypemobilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pilihtypemobilActionPerformed

    private void RdBTNFasilitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdBTNFasilitasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RdBTNFasilitasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNkembali;
    private javax.swing.JButton BTNlanjut1;
    private javax.swing.JComboBox CMBOXbulankembali;
    private javax.swing.JComboBox CMBOXbulanpinjam;
    private javax.swing.JComboBox CMBOXtahunkembali;
    private javax.swing.JComboBox CMBOXtahunpinjam;
    private javax.swing.JComboBox CMBOXtanggalkembali;
    private javax.swing.JComboBox CMBOXtanggalpinjam;
    private javax.swing.JRadioButton RdBTNAll;
    private javax.swing.JRadioButton RdBTNFasilitas;
    private javax.swing.JRadioButton RdBTNSopir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> comboboxMobil;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
