/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rentkuyyoi;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JSpinner;
import javax.swing.JTextField;

/**
 *
 * @author Firhan
 */
public class ShowTransaksi extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel3
     */
    public ShowTransaksi() {
        initComponents();
    }

    public JButton getBTNmenu1() {
        return BTNmenu1;
    }

    public JTextField getTXTidTransaksi() {
        return TXTidTransaksi;
    }

    public JTextField getTXTtanggalpeminjaman() {
        return TXTtanggalpeminjaman;
    }

    public JTextField getTXTtanggalpengembalian() {
        return TXTtanggalpengembalian;
    }

    
    public JTextField getTXTtipeMobil() {
        return TXTtipeMobil;
    }

    public JTextField getTXTtotalharga() {
        return TXTtotalharga;
    }

    public JTextField getTXTidCustomer() {
        return TXTidCustomer;
    }

    public void setTXTidCustomer(int idCustomer) {
        this.TXTidCustomer.setText(String.valueOf(idCustomer));
    }
    
    public void setTXTtanggalpeminjaman(int tanggalpinjam){
        this.TXTtanggalpeminjaman.setText(String.valueOf(tanggalpinjam));
    }

    public void setTXTidTransaksi(int idTransaksi) {
        this.TXTidTransaksi.setText(String.valueOf(idTransaksi));
    }
    
    public void setTXTtanggalpengembalian(int tanggalkembali){
        this.TXTtanggalpengembalian.setText(String.valueOf(tanggalkembali));
    }

    public void setTXTtipeMobil(String tipeMobil) {
        this.TXTtipeMobil.setText(tipeMobil);
    }

    public void setTXTtotalharga(int totalharga) {
        this.TXTtotalharga.setText(String.valueOf(totalharga));
    }
    
    public void addListener(ActionListener e){
        BTNmenu1.addActionListener(e);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        TXTtipeMobil = new javax.swing.JTextField();
        TXTtotalharga = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TXTidTransaksi = new javax.swing.JTextField();
        Jlabel = new javax.swing.JLabel();
        TXTidCustomer = new javax.swing.JTextField();
        TXTtanggalpeminjaman = new javax.swing.JTextField();
        TXTtanggalpengembalian = new javax.swing.JTextField();
        BTNmenu1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jInternalFrame1.setTitle("Show Transaksi");
        jInternalFrame1.setVisible(true);
        jInternalFrame1.getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\K u l i a h\\Pemrograman Berorientasi Objek (PBO)\\TubesKelompok3\\NetBeansProjects\\NetBeansProjects\\RentKuyYoi\\src\\rentkuyyoi\\logo-mobil3.png")); // NOI18N
        jInternalFrame1.getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 0, 370, 130);

        jPanel1.setBackground(new java.awt.Color(195, 152, 107));

        label1.setText("Type Mobil");

        jLabel2.setText("Tgl Pemnjaman");

        jLabel3.setText("Tgl Pengembalian");

        jLabel4.setText("Total Harga");

        jLabel5.setText("Id Transaksi");

        TXTidTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTidTransaksiActionPerformed(evt);
            }
        });

        Jlabel.setText("Id Customer");

        TXTidCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTidCustomerActionPerformed(evt);
            }
        });

        TXTtanggalpeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTtanggalpeminjamanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(95, 95, 95)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TXTidCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                            .addComponent(TXTtotalharga)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5)
                                .addComponent(Jlabel)))
                        .addGap(89, 89, 89)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TXTidTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                            .addComponent(TXTtipeMobil)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(79, 79, 79)
                        .addComponent(TXTtanggalpeminjaman))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(68, 68, 68)
                        .addComponent(TXTtanggalpengembalian)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTidTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jlabel)
                    .addComponent(TXTidCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXTtipeMobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TXTtanggalpeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TXTtanggalpengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TXTtotalharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        jInternalFrame1.getContentPane().add(jPanel1);
        jPanel1.setBounds(90, 130, 400, 230);

        BTNmenu1.setText("Menu Utama");
        BTNmenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNmenu1ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(BTNmenu1);
        BTNmenu1.setBounds(70, 410, 100, 23);
        jInternalFrame1.getContentPane().add(jLabel6);
        jLabel6.setBounds(250, 380, 0, 0);

        jLabel7.setIcon(new javax.swing.ImageIcon("E:\\K u l i a h\\Pemrograman Berorientasi Objek (PBO)\\TubesKelompok3\\NetBeansProjects\\NetBeansProjects\\RentKuyYoi\\src\\rentkuyyoi\\bg.jpg")); // NOI18N
        jInternalFrame1.getContentPane().add(jLabel7);
        jLabel7.setBounds(0, -40, 860, 520);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );

        try {
            jInternalFrame1.setIcon(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
    }// </editor-fold>//GEN-END:initComponents

    private void BTNmenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNmenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNmenu1ActionPerformed

    private void TXTidTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTidTransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTidTransaksiActionPerformed

    private void TXTidCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTidCustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTidCustomerActionPerformed

    private void TXTtanggalpeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTtanggalpeminjamanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTtanggalpeminjamanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNmenu1;
    private javax.swing.JLabel Jlabel;
    private javax.swing.JTextField TXTidCustomer;
    private javax.swing.JTextField TXTidTransaksi;
    private javax.swing.JTextField TXTtanggalpeminjaman;
    private javax.swing.JTextField TXTtanggalpengembalian;
    private javax.swing.JTextField TXTtipeMobil;
    private javax.swing.JTextField TXTtotalharga;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
